[package]
name = "barish"
version = "0.1.0"
edition = "2021"
description = "weather info in your terminal provided by bbc"
license = "MIT"

[dependencies]
curl = "0.4.44"
serde = { version = "1.0.160", features = [ "derive" ] }
serde-xml-rs = "0.6.0"
